# Generated by Django 2.2 on 2019-08-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='client',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('IM', 'Immediate'), ('SIM', 'Semi-Immediate'), ('NIM', 'Not-Immediate')], default=3, max_length=20),
        ),
    ]
