# Generated by Django 2.2 on 2019-08-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20190814_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('IM', 'Immediate'), ('SIM', 'Semi-Immediate'), ('NIM', 'Not-Immediate')], default='NIM', max_length=20),
        ),
    ]
