# Generated by Django 2.2 on 2019-08-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_response'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['priority']},
        ),
    ]
