# Generated by Django 2.2 on 2019-08-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20190814_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-priority']},
        ),
    ]
