# Generated by Django 2.2 on 2019-08-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20190814_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Immediate'), (2, 'Semi-Immediate'), (3, 'Not-Immediate')], default=3),
        ),
    ]
