# Generated by Django 2.2 on 2019-08-15 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Comment'),
        ),
    ]
